enable:
  issues: true
  prs: true

comments:
  issues: |
    Thanks for opening this issue!
    I have applied labels to your issue 🏷

    Your issue will be reviewed by a maintainer as soon as possible.
  prs: |
    Thanks for the contribution!
    I have applied labels to your pull request 🏷

    Your pull request will be reviewed by a maintainer as soon as possible.

labels:
  'bug':
    include:
      - '\bbug[s]?\b'
      - '\bfix(e[ds])?\b'
      - '\bissue[s]?\b'
      - '\berror[s]?\b'
      - '\bprevent\b'
    branches:
      - 'master'
      - 'develop'

  'dependencies':
    include:
      - '\bdep[s]?\b'
      - '\bdependenc(y|ies)\b'
      - '\bbump\b'
      - '\bupdate\b'
      - '\bcargo\b'

  'documentation':
    include:
      - '\bdoc[s]?\b'
      - '\bdocumentation\b'
      - '\breadme\b'
      - '\btypo[s]?\b'

  'duplicate':
    include:
      - '\bduplicate\b'

  'enhancement':
    include:
      - '\bfeat(ure)?\b'
      - '\benhancement[s]?\b'
      - '\bimplement(ation)?\b'
      - '\banalytics\b'
      - '\bprofiling\b'

  'github_actions':
    include:
      - '\bworkflow\b'
      - '\baction[s]?\b'
      - '\bci\b'
      - '\bgithub action[s]?\b'

  'help wanted':
    include:
      - '\bhelp( me)?\b'

  'question':
    include:
      - '\bquestion\b'
      - '\?'

  'rust':
    include:
      - '\brust\b'
      - '\brefactor\b'
      - '\blib\b'

  'wontfix':
    include:
      - '\bwontfix\b'
      - '\bwont fix\b'
      - '\bwon\'t fix\b'
