sonar.projectKey=boul2gom_yt-dlp
sonar.organization=boul2gom

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Python version for scripts/ folder
sonar.python.version=3