name: "🔌 Github CI - Production"

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sonarcloud-analysis:
    name: 🔍 SonarCloud analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📁 Check out the repository
        uses: actions/checkout@v6.0.2
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: false

      - name: 🔍 Scan with SonarCloud
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}